version: '3.9'

volumes:
  postgres_data_fastapi:

services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi
    restart: on-failure
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    env_file:
      - ./.env

  postgres_fastapi:
    image: postgres:latest
    container_name: postgres_fastapi
    ports:
      - "5448:5432"
    volumes:
      - postgres_data_fastapi:/var/lib/postgresql/data/
    env_file:
      - ./.env


